services:
  postgres:
    image: postgres:15
    container_name: account-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accountdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
